name: Update Gallery

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  update-gallery:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Generate image list
      run: |
        mkdir -p assets
        echo "const imageList = [" > image-list.js
        find assets -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" -o -iname "*.webp" -o -iname "*.svg" \) -exec basename {} \; | sort | sed 's/.*/"&",/' >> image-list.js
        echo "];" >> image-list.js
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add image-list.js
        git diff --staged --quiet || git commit -m "Auto-update image list [skip ci]"
        git push
